// src/components/Controls/controlsSlice.js
import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  playing: false,
  played: 0,
  elapsedTime: '0:00',
  totalDuration: '0:00',
  muted: false,
  playbackRate: 1,
  volume: 50, // Initially 50% volume
};

export const controlsSlice = createSlice({
  name: 'controls',
  initialState,
  reducers: {
    setPlaying: (state, action) => {
      state.playing = action.payload;
    },
    setPlayed: (state, action) => {
      state.played = action.payload;
    },
    setElapsedTime: (state, action) => {
      state.elapsedTime = action.payload;
    },
    setTotalDuration: (state, action) => {
      state.totalDuration = action.payload;
    },
    setMuted: (state, action) => {
      state.muted = action.payload;
    },
    setPlaybackRate: (state, action) => {
      state.playbackRate = action.payload;
    },
    setVolume: (state, action) => {
      state.volume = action.payload;
    },
  },
});

// Action creators generated from the slice
export const {
  setPlaying,
  setPlayed,
  setElapsedTime,
  setTotalDuration,
  setMuted,
  setPlaybackRate,
  setVolume,
} = controlsSlice.actions;

// Selector to get the controls state
export const selectControls = (state) => state.controls;

// Reducer function generated by createSlice
export default controlsSlice.reducer;
